    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      # NYTT: psql-klient (ger pg_isready och psql)
      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres (extra gardering)
        run: |
          for i in {1..60}; do
            pg_isready -h localhost -p 5433 -U betting && break
            sleep 1
          done

      - name: Create test database if missing
        env:
          PGPASSWORD: betting
        run: |
          psql -h localhost -p 5433 -U betting -d postgres -tc "SELECT 1 FROM pg_database WHERE datname='betting_core'" | grep -q 1 \
            || psql -h localhost -p 5433 -U betting -d postgres -c "CREATE DATABASE betting_core"
          psql -h localhost -p 5433 -U betting -d postgres -tc "SELECT 1 FROM pg_database WHERE datname='betting_core_test'" | grep -q 1 \
            || psql -h localhost -p 5433 -U betting -d postgres -c "CREATE DATABASE betting_core_test"

      - name: Run Alembic migrations (main)
        run: |
          alembic -c db/alembic.ini upgrade head

      - name: Run Alembic migrations (test)
        env:
          DATABASE_URL: ${{ env.TEST_DATABASE_URL }}
        run: |
          alembic -c db/alembic.ini upgrade head

      # NYTT: seed för MAIN-DB
      - name: Seed reference data (main)
        env:
          PGPASSWORD: betting
        run: |
          psql -h localhost -p 5433 -U betting -d betting_core -v ON_ERROR_STOP=1 -f db/seed_test.sql

      # NYTT: seed för TEST-DB (som testerna använder)
      - name: Seed reference data (test)
        env:
          PGPASSWORD: betting
        run: |
          psql -h localhost -p 5433 -U betting -d betting_core_test -v ON_ERROR_STOP=1 -f db/seed_test.sql

      - name: Run tests
        run: |
          pytest -q --cov=app --cov-report=term-missing
