name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: betting
          POSTGRES_PASSWORD: betting
          POSTGRES_DB: betting_core
        ports:
          - 5433:5432        # <— bind 5432 i containern till 5433 på hosten
        options: >-
          --health-cmd="pg_isready -U betting -d betting_core_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      PYTHONPATH: .
      TZ: UTC
      RATE_LIMIT_ENABLED: "false"   # stäng av Redis i CI
      DATABASE_URL: postgresql+psycopg://betting:betting@localhost:5433/betting_core_test
      DB_HOST: localhost
      DB_PORT: "5433"
      DB_USER: betting
      DB_PASSWORD: betting
      DB_NAME: betting_core

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install system deps (psql client)
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5433 -U betting -d betting_core_test && break
            sleep 1
          done

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run Alembic migrations
        run: alembic -c db/alembic.ini upgrade head

      - name: Run tests
        run: pytest -q --cov=app --cov-report=term-missing